# Generated by Django 5.2 on 2025-04-18 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        ('technologies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills_coding',
            field=models.ManyToManyField(blank=True, to='technologies.codinglanguage'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills_tools',
            field=models.ManyToManyField(blank=True, to='technologies.tool'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
