# Generated by Django 5.2 on 2025-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
